### ISSUE TITLE
does not work with qunit 1.16.0

### ISSUE THREAD

**Issue by stefanpenner** [dockyard/ember-qunit-notifications#4]
the toolbar fails to be found

**Comment by jme783** [comment]
Is there a fix for this @stefanpenner ? I'm getting the toolbar error when I run `ember test --server`

**Comment by rwjblue** [comment]
It works with 1.17

**Comment by jme783** [comment]
Thanks for the reply @rwjblue! I upgraded quinit to 1.17.0 and ember-qunit-notifications to 0.0.7 and am still getting the error: `Uncaught TypeError: Cannot read property 'appendChild' of null at http://localhost:7357/assets/test-support-6e02e6ef8562dfa03b748d95da6cd52d.js, line 2828` when I run `ember test --server`. Here's my package.json:

```
{
  "name": "fleet-management",
  "dependencies": {
    "handlebars": "~1.3.0",
    "jquery": "^1.11.1",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.12",
    "ember-resolver": "~0.1.7",
    "loader.js": "stefanpenner/loader.js#1.0.1",
    "ember-cli-shims": "stefanpenner/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "stefanpenner/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "1.17.0",
    "bourbon": "~4.0.2",
    "neat": "~1.7.0",
    "ionicons": "1.5.2",
    "moment": "~2.8.4",
    "ember-simple-auth": "0.7.2",
    "ember-easyForm": "http://builds.dockyard.com.s3.amazonaws.com/ember-easyForm/canary/daily/20140202/ember-easyForm.js",
    "ember-uploader": "~0.3.2"
  }
}
```

Any thoughts?

**Comment by amercier** [comment]
This should have been fixed since dockyard/qunit-notifications v0.0.6.
See dockyard/qunit-notifications/issues/17 for details.

@jme783 @stefanpenner @rwjblue I'll look into this

**Comment by amercier** [comment]
@jme783 **ember-qunit-notifications** and **qunit-notifications** are installed in **ember-cli** as Bower components. Therefore, the version of QUnit it depends on is defined in `bower.json`, not in `package.json`. Could you you give the content of your `bower.json`, please?

QUnit v1.17.0 should be automatically installed though. Could you try reinstalling all Bower components after cleaning Bower cache:
```
bower cache clean
rm -rf bower_components
bower install
```

**Comment by jme783** [comment]
Ah thanks @amercier you are totally right, it was `bower.json`. What actually resolved the issue for me was bumping my `ember-cli` version to the latest, 0.1.15
